#! /bin/sh

bspc monitor -d i ii iii iv v vi vii viii ix x

bspc config border_width            0
bspc config window_gap             40
bspc config top_padding            70
bspc config bottom_padding          0
bspc config right_padding           0
bspc config left_padding            0

bspc config focused_border_color  "#2b2b2b"
bspc config active_border_color   "#2b2b2b"
bspc config normal_border_color   "#ececec"

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#mouse actions
bspc config pointer_modifier     mod4
bspc config pointer_action1      move
bspc config pointer_action2    resize
bspc config click_to_focus       true

bspc rule -a Conky sticky=on manage=off lower=on

sh $HOME/.config/Citrus/polybar/launch.sh
